language: c
sudo: false

matrix:
  include:
  - os: osx
    env: BUILDSYS=meson
    compiler: clang
  - os: linux
    dist: "trusty"
    env: BUILDSYS=meson
  - os: osx
    env: BUILDSYS=automake
    compiler: clang
  - os: linux
    dist: "trusty"
    env: BUILDSYS=automake


install:
  - export PATH="`pwd`/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "osx"  ]]; then rvm get stable; brew update && brew install python3 ninja pkg-config automake libtool; echo "done"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - pip3 install meson

script:
  - if [[ "$BUILDSYS" == "meson" ]]; then meson builddir && ninja -C builddir && ninja -C builddir test; fi
  - if [[ "$BUILDSYS" == "automake" ]]; then ./autogen.sh && ./configure --prefix="$PWD/install" CPPFLAGS="-Wall -Werror --std=c99" && make && make check && make install; fi


after_success:
  - if [[ "$BUILDSYS" == "automake" && "$TRAVIS_OS_NAME" == "linux" ]]; then for direct in $(find . -type d); do (cd "$direct"; for file in $(ls | grep "\\.gcno$"); do gcov -b "$file"; done)  done; bash <(curl -s https://codecov.io/bash)

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sv8yElN3h+ZaivMLyY4CMz6ZXLRCDABxnkiKdmJGzPKClpLSpXf7vzFqwWRN3G9hDvVzPsO9uEPXhx8RRn2dK8HSbWOsHc9H3KNejLmK/UgPR9pcmcP3FBUOq3y3q8hHJwQjsfbgjfaYjpca0fo/l3i5q58xBEsPcp6uxrMKAoE9y14K7T2PYQGT20JMoMeUekgnPyrwBNIOzTPv1EacTnN3q2D6A5xU5RTyQKnp+NP9K1G4vUjg5c/58/GwGqjiXuHFMb8WqEYly4LZnUZ9m52/85ZGF2aGm9RT55y+VRvsSdmlZKnUbFXNP/IUr7FzC5JlXtz58VqC8Ipkqx1/MEVB5pvtha27oK27ZTWfAmv+T8Dy2U5u1YO+jnp1mbWg/bVN500D2IBTNNsROxicTsDLYNvo4tTixHVFaiZ8F5/tulirGOrtRwTnYMWRgT0s47N1ln56DCsJirOKPqGK1QZrhYDR1l4h7421fHuNljrQ56MT/Ew3Olu9ss/WBo8Hhz64+cxdiBGlPtUeB8etdhNDzASgk8DIrP7DFZ9RMSbcJWPUpbHZBKEX287LhqNkzN+Yt/zbg5JrcMz97Fgd9SGjD4dQFLSjc6c5/9CuY0CkqCRQhXUe31nNV5v0Gxnd0WNgyWMPDJWybugh91gCnrAUty8WyLtkMl91sNeg+DA="

addons:
  coverity_scan:
    project:
      name: "zeehio/saga"
      description: "<Your project description here>"
    notification_email: sergioller@gmail.com
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
  apt:
    packages:
    - autotools-dev
    - autoconf
    - automake
    - libtool
    - pkg-config
    - python3
    - python3-pip

